# Copyright (C) 2017-2019 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/gte-common/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/gte-common/proprietary/vendor/lib/libaudiosa.so:$(TARGET_COPY_OUT_VENDOR)/lib/libaudiosa.so \
    vendor/samsung/gte-common/proprietary/vendor/lib/libmysound.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmysound.so \
    vendor/samsung/gte-common/proprietary/vendor/lib/soundfx/libaudioeffectoffload.so:$(TARGET_COPY_OUT_VENDOR)/lib/soundfx/libaudioeffectoffload.so \
    vendor/samsung/gte-common/proprietary/vendor/lib/soundfx/libmyspace.so:$(TARGET_COPY_OUT_VENDOR)/lib/soundfx/libmyspace.so
